### ISSUE TITLE
訳語の相談: do_action はそのままで良いでしょうか？

### ISSUE THREAD

**Issue by miminari** [jawordpressorg/community-handbook#27]
do_action という多分[関数リファレンス/do action - WordPress Codex 日本語版](
https://wpdocs.osdn.jp/%E9%96%A2%E6%95%B0%E3%83%AA%E3%83%95%E3%82%A1%E3%83%AC%E3%83%B3%E3%82%B9/do_action)にひっかけたイベント名が出てくるのですが、そのままで良いですか？

> do_action is a charity hackathon that uses WordPress to uplift local communities.

ということらしいです。

**Comment by nukaga** [comment]
はい。まだ日本で開催されたことはないのですが、チャリティーハッカソンの名前なので、WordCamp  と同じようにそのまま do_action で良いと思います。

**Comment by miminari** [comment]
WordCampに出てくるんですね！チェック不足ですみません。ありがとうございました！
closeしますー
