### ISSUE TITLE
翻訳用語集について

### ISSUE THREAD

**Issue by ixkaito** [jawordpressorg/community-handbook#40]
翻訳用語集、二重であるのはよくないのでどちらかに統一しましょう。あと名前も、例えば「翻訳用語集」に統一しましょう。
https://github.com/jawordpressorg/community-handbook/blob/master/glossary.md
https://github.com/jawordpressorg/community-handbook/wiki/%E5%8D%98%E8%AA%9E%E5%B8%B3

**Comment by nukaga** [comment]
先にwikiを作ったのですが、glossary.mdはAPI的にも使えると聞いていまして、そちらに統一が良いと思います。
https://wpja.slack.com/archives/CB6KS14BS/p1529511319000603

**Comment by ixkaito** [comment]
Wiki の方を削除しました！
