### ISSUE TITLE
WordSlackの #community-translate チャンネルへの通知について

### ISSUE THREAD

**Issue by nukaga** [jawordpressorg/community-handbook#41]
このリポジトリのアクティビティをSlackに通知しても良いかと思ったのですが、いかがでしょうか？

**Comment by shinyabw** [comment]
おつかれさまです。 ideas チャンネルをみていて思うのですが、 GitHub 通知の表示が読みにくのと、話題ごとにグループ (スレッド) になっておらず、slack 上でのコミュニケーションを破綻させていると感じています。現状では、 ideas チャンネルを読みたいとは思えないというか、読むのが凄く大変です。つきましては アクティビティ を Slack に通知は反対です。通知が必要な場合は、 Notifications > Subscribe で、GitHub からメールの通知を受ける方が理にかなっているのではないかと思っています。通知が必要な人には、 GitHub の通知機能を教えてあげることも必要かなと思っています。よろしくお願いします。

**Comment by miminari** [comment]
そうですよね。確かに Slack 上で通知内容を読もうと思ったことがないです。

（実は、BEFORE WordSlack の私にとっては Slack はマンツーマンの会話ツールか、GitHub他の通知ツールでしかなかったので、多人数のコミュニティツールとして機能しているのを拝見して逆のカルチャーショックをこっそり受けたことをココに記しておきます…）

**Comment by nukaga** [comment]
では、特に他に通知があった方が良い！という意見がなさそうだったら、このまま通知はなしでいこうかと思います。もう少しだけこのissueを開けたまま意見を待ってみますね。（2日ぐらい？）

**Comment by shinyabw** [comment]
了解です。それと、全体の通知は、 Watch でした。これと同じものを、 Read Me に入れるといいかなと思いました。

https://github.com/jawordpressorg/ideas/issues/32

**Comment by miya0001** [comment]
`ideas` は目的上なんでもかんでも通知を送ってますが、`master` へのマージだけ通知するとかですかね。

**Comment by nukaga** [comment]
あ、master へのマージだけ通知いいですね。進行状況をなんとなく Slackでもわかるようにしたいな、という感じだったので、それだったらうるさすぎもせず良い感じな気がします。

**Comment by nukaga** [comment]
watchへの追加の推奨は、ここの目的上大切なことではないように思うので、Readme は翻訳まわりの情報だけにしておいた方が読みやすいかなと思いました。それについては、やっぱり欲しい！ということであればプルリクエストか別のisseueを立てていただく方がわかりやすそうです。

**Comment by nukaga** [comment]
ちょっと様子を見ていたのですが、GitHubでの動きがあっても、それをチャンネルに書き込まないといけないという感じなので、プルリクエストがあった時と、プルリクエストがマージされた時だけチャンネルにお知らせが流れるようにしてみました。
これでまた様子を見て、コミュニケーションが阻害されると感じるようであれば、通知を減らす、もしくは無くす。反対にもっと知りたいようであれば増やすというようなissueをそれぞれ立てていただくのがわかりやすいかと思いました。
というわけで、こちらクローズしますね。
