### ISSUE TITLE
ブランチの削除

### ISSUE THREAD

**Issue by ixkaito** [jawordpressorg/community-handbook#56]
@jawordpressorg/community-handbook-translate コミッターのみなさんがブラウザでプルリク送ると自動的にブランチが作成されますので、マージされたやつはなるべく削除していってくださいね。メンテナーとして僕が削除してもよければやりますので遠慮なくお申し付けください。

**Comment by nukaga** [comment]
気になっていたところでした。自分の分、削除しました！
ありがとうございます。
また他の方の分でブラウザからのプルリクについて、 @ixkaito さんや @miminari さんがメンテナンスされるのは問題ないと思います。
