### ISSUE TITLE
英語の変更を検知する

### ISSUE THREAD

**Issue by hideokamoto** [jawordpressorg/community-handbook#74]
miruconさんの https://mirucon.github.io/required-ja/ みてて、
これcommunity-handbookの方でもやれそうかなと思ったんですがどうでしょう？
https://github.com/mirucon/required-ja/blob/master/track/TrackChanges.js

ページ数が多いのでそのまま真似するわけにはいかないと思いますが、
更新が必要そうかどうかの判定だけとかでもいけないかなと。

## meetup handbook

```
$ curl https://make.wordpress.org/community/wp-json/wp/v2/meetup-handbook | jq ".[] | .title.rendered"

"Incident Reporting"
"WordPress 15th Anniversary Celebrations"
"When a Group Leaves the Chapter Program"
"Suggestions for Meetup Content"
"Diversity Speaker Training Workshop"
"Contributor Day"
"Additional Preparation"
"Maintaining Communication"
"Organising Hosting"
"Finding Sponsors"
```

## WordCamp Handbook

```
$ curl https://make.wordpress.org/community/wp-json/wp/v2/wordcamp-handbook | jq ".[] | .title.rendered"

"Data Handling Best Practices"
"Computer security best practices"
"Incident Reporting"
"Life-threatening allergies"
"Swag Source Files"
"PayPal Guest Checkout"
"Financial Data Privacy and Retention"
"Banners and Flyers"
"Adding videos to your WordCamp site"
"Sponsor agreements"
```

**Comment by nukaga** [comment]
ありがとうございます！
https://github.com/jawordpressorg/ideas/issues/24
で出ているものですね。

上記のissueの様子を見てたのですが、もう進めちゃって良さそうな感じなのでしょうか？

**Comment by ixkaito** [comment]
はい、これは進めていきたいと思っています。

**Comment by miya0001** [comment]
* @mirrucon くんの仕組みだと100ページ以上のページがあるさいに動作しない。
* メニューを自動生成＆翻訳可能にしたい。
  * 未翻訳のページがあることも検知＆表示したい。
* あと他の言語も想定してあげたいこと。たとえばドイツチームとかイタリアチームでは需要があると思う。
* CORS が許可されていないので何らかのバックエンドの仕組みが必要になるかもしれない。（現状はTravisで行ける気はしてる。）
* 仕組みそのものは別のリポジトリにして汎用的にしたい。

などなどいろいろあるので、引き続き https://github.com/jawordpressorg/ideas/issues/24 で検討します。

**Comment by hideokamoto** [comment]
ありがとうございます！
ideasの方にissueあったんですね。

やりとりが散らばってもよくないかなと思いますので、
こちらはクローズして jawordpressorg/ideas#24 の方追うようにします。
