### ISSUE TITLE
翻訳担当の担当中のフラグをどう扱うか

### ISSUE THREAD

**Issue by miminari** [jawordpressorg/community-handbook#9]
ハンドブックは現在ページ単位で担当を名乗り出てもらう形だと思いますが、GitHubでやる場合は行単位で担当者が変わる事も、複数人で翻訳してもらうことも（やるやらないは別にして）可能になります。慣れてくると気軽にコントリビュートしてもらえるのでは、とも思うのですが … 。

ひとまず、担当中のフラグ（誰かがそのページを翻訳中であることの目印）をどうするか、なにか良い案ありますでしょうか？

パラパラとGitHubで翻訳をしているリポジトリを見ていると、

- Issuesで宣言（アサインを自分にする）してラベル（In Progressなど）を貼って管理
- 着手予定の宣言をするIssueに宣言していく

というパターンがありました。
あと監訳者にフォローをお願いできる仕組みとか、カンバンの利用とか、色々参考になったので、まずは参照させてもらったリポジトリを書き出しておきます。

参照リポジトリ：
- https://github.com/DjangoGirlsJapan/tutorialJP/wiki/GitHubでの翻訳作業の流れ
- https://github.com/enja-oss/Sass
- https://github.com/gophersjp/go/wiki/翻訳協力フロー
- https://github.com/mozilla-japan/translation
- https://github.com/postdcc/translation_request
- https://github.com/html5j-english/webplatform

**Comment by ixkaito** [comment]
ページをまるごと担当する (量が多い) 場合は issue 立ててラベルつけるのがいいかもしれません。1行とか、一瞬で終わる場合はそのままプルリク送ってもらったらいいように思います。
